package hvv_aviewer;

import java.util.Calendar;
import java.util.GregorianCalendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yaroslav
 */
public class HVV_AV_MainFrame extends javax.swing.JFrame {
    GregorianCalendar m_gdtmDate;
    private HVV_ArchiveViewer theApp;
            
    /**
     * Creates new form HVV_AV_MainFrame
     */
    public HVV_AV_MainFrame( HVV_ArchiveViewer app) {
        initComponents();
        theApp = app;
        setTitle( "Модуль просмотра архивных данных, v.1.0.0.0 (2015.12.02 11:07), (C) ФЛАВТ 2015.");
        m_gdtmDate = ( GregorianCalendar) Calendar.getInstance();
        updateDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        lblPoint1 = new javax.swing.JLabel();
        lblStartDay = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblPoint2 = new javax.swing.JLabel();
        lblStartMonth = new javax.swing.JLabel();
        lblHour = new javax.swing.JLabel();
        lblDblPoint = new javax.swing.JLabel();
        lblMinutes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPoint3 = new javax.swing.JLabel();
        lblDay1 = new javax.swing.JLabel();
        lblYear1 = new javax.swing.JLabel();
        lblPoint4 = new javax.swing.JLabel();
        lblMonth1 = new javax.swing.JLabel();
        lblHour1 = new javax.swing.JLabel();
        lblDblPoint1 = new javax.swing.JLabel();
        lblMinutes1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 1000));
        setMinimumSize(new java.awt.Dimension(1200, 1000));
        setResizable(false);
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VC.00А.Контур контроля форвакуума.Состояние", "VC.001.Насос Edwards.Состояние", "VC.04A.Датчик.Показание", "VC.16A.РРГ (О2).Состояние", "VC.16A.РРГ (О2).Уставка", "VC.16A.РРГ (О2).Показание", "HV.Рубильник.Состояние", "HV.ЛГ1.Анод.Состояние", "HV.ЛГ1.Анод.Ток", "HV.ЛГ1.Анод.Напряжение", "HV.ЛГ1.Штенгель.Состояние", "HV.ЛГ1.Штенгель.Ток", "HV.ЛГ1.Штенгель.Напряжение", "HV.ЛГ2.Анод.Состояние", "HV.ЛГ2.Анод.Ток", "HV.ЛГ2.Анод.Напряжение", "HV.ЛГ2.Штенгель.Ток", "HV.ЛГ2.Штенгель.Напряжение", "HV.ЛГ3.Анод.Ток", "HV.ЛГ3.Анод.Напряжение", "HV.ЛГ3.Штенгель.Ток", "HV.ЛГ3.Штенгель.Напряжение", "HV.ЛГ4.Анод.Ток", "HV.ЛГ4.Анод.Напряжение", "HV.ЛГ4.Штенгель.Ток", "HV.ЛГ4.Штенгель.Напряжение", "HV.ЛГ5.Анод.Ток", "HV.ЛГ5.Анод.Напряжение", "HV.ЛГ5.Штенгель.Ток", "HV.ЛГ5.Штенгель.Напряжение", "HV.ЛГ6.Анод.Ток", "HV.ЛГ6.Анод.Напряжение", "HV.ЛГ6.Штенгель.Ток", "HV.ЛГ6.Штенгель.Напряжение", "HV.ЛГ7.Анод.Ток", "HV.ЛГ7.Анод.Напряжение", "HV.ЛГ7.Штенгель.Ток", "HV.ЛГ7.Штенгель.Напряжение", "HV.ЛГ8.Анод.Ток", "HV.ЛГ8.Анод.Напряжение", "HV.ЛГ8.Штенгель.Ток", "HV.ЛГ8.Штенгель.Напряжение" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(10, 920, 410, 40);

        lblPoint1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblPoint1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoint1.setText(".");
        getContentPane().add(lblPoint1);
        lblPoint1.setBounds(510, 920, 10, 40);

        lblStartDay.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblStartDay.setText("30");
        lblStartDay.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblStartDayMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblStartDay);
        lblStartDay.setBounds(460, 920, 50, 40);

        lblYear.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblYear.setText("2015");
        lblYear.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblYearMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblYear);
        lblYear.setBounds(580, 920, 100, 40);

        lblPoint2.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblPoint2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoint2.setText(".");
        getContentPane().add(lblPoint2);
        lblPoint2.setBounds(570, 920, 10, 40);

        lblStartMonth.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblStartMonth.setText("12");
        lblStartMonth.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblStartMonthMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblStartMonth);
        lblStartMonth.setBounds(520, 920, 50, 40);

        lblHour.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblHour.setText("20");
        lblHour.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblHourMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblHour);
        lblHour.setBounds(690, 920, 50, 40);

        lblDblPoint.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblDblPoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDblPoint.setText(":");
        getContentPane().add(lblDblPoint);
        lblDblPoint.setBounds(740, 920, 10, 40);

        lblMinutes.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblMinutes.setText("12");
        lblMinutes.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblMinutesMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblMinutes);
        lblMinutes.setBounds(750, 920, 50, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1178, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 1180, 890);

        lblPoint3.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblPoint3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoint3.setText(".");
        getContentPane().add(lblPoint3);
        lblPoint3.setBounds(900, 920, 10, 40);

        lblDay1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblDay1.setText("30");
        lblDay1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDay1MouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDay1);
        lblDay1.setBounds(850, 920, 50, 40);

        lblYear1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblYear1.setText("2015");
        lblYear1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblYear1MouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblYear1);
        lblYear1.setBounds(970, 920, 100, 40);

        lblPoint4.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblPoint4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoint4.setText(".");
        getContentPane().add(lblPoint4);
        lblPoint4.setBounds(960, 920, 10, 40);

        lblMonth1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblMonth1.setText("12");
        lblMonth1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblMonth1MouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblMonth1);
        lblMonth1.setBounds(910, 920, 50, 40);

        lblHour1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblHour1.setText("20");
        lblHour1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblHour1MouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblHour1);
        lblHour1.setBounds(1080, 920, 50, 40);

        lblDblPoint1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblDblPoint1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDblPoint1.setText(":");
        getContentPane().add(lblDblPoint1);
        lblDblPoint1.setBounds(1130, 920, 10, 40);

        lblMinutes1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblMinutes1.setText("12");
        lblMinutes1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblMinutes1MouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblMinutes1);
        lblMinutes1.setBounds(1140, 920, 50, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(968, 10, 220, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHourMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblHourMouseWheelMoved
        m_gdtmDate.add( Calendar.HOUR, -1 * evt.getWheelRotation());
        updateDate();
    }//GEN-LAST:event_lblHourMouseWheelMoved

    private void lblMinutesMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblMinutesMouseWheelMoved
        m_gdtmDate.add( Calendar.MINUTE, -1 * evt.getWheelRotation());
        updateDate();
    }//GEN-LAST:event_lblMinutesMouseWheelMoved

    private void lblYearMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblYearMouseWheelMoved
        m_gdtmDate.add( Calendar.YEAR, -1 * evt.getWheelRotation());
        updateDate();
    }//GEN-LAST:event_lblYearMouseWheelMoved

    private void lblStartMonthMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblStartMonthMouseWheelMoved
        m_gdtmDate.add( Calendar.MONTH, -1 * evt.getWheelRotation());
        updateDate();
    }//GEN-LAST:event_lblStartMonthMouseWheelMoved

    private void lblStartDayMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblStartDayMouseWheelMoved
        m_gdtmDate.add( Calendar.DAY_OF_MONTH, -1 * evt.getWheelRotation());
        updateDate();
    }//GEN-LAST:event_lblStartDayMouseWheelMoved

    private void lblDay1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblDay1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDay1MouseWheelMoved

    private void lblYear1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblYear1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblYear1MouseWheelMoved

    private void lblMonth1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblMonth1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMonth1MouseWheelMoved

    private void lblHour1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblHour1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHour1MouseWheelMoved

    private void lblMinutes1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblMinutes1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMinutes1MouseWheelMoved

    private void updateDate() {
        
        lblStartDay.setText( ( m_gdtmDate.get( Calendar.DAY_OF_MONTH) < 10 ? "0" : "") +
                        m_gdtmDate.get( Calendar.DAY_OF_MONTH));
        
        lblStartMonth.setText( ( m_gdtmDate.get( Calendar.MONTH) + 1 < 10 ? "0" : "") +
                          ( m_gdtmDate.get( Calendar.MONTH) + 1));
        
        lblYear.setText( ( m_gdtmDate.get( Calendar.YEAR) < 10 ? "0" : "") +
                         m_gdtmDate.get( Calendar.YEAR));
        
        lblHour.setText( ( m_gdtmDate.get( Calendar.HOUR_OF_DAY) < 10 ? "0" : "") +
                         m_gdtmDate.get( Calendar.HOUR_OF_DAY));
        
        lblMinutes.setText( ( m_gdtmDate.get( Calendar.MINUTE) < 10 ? "0" : "") +
                            m_gdtmDate.get( Calendar.MINUTE));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HVV_AV_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HVV_AV_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HVV_AV_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HVV_AV_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HVV_AV_MainFrame( null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDay1;
    private javax.swing.JLabel lblDblPoint;
    private javax.swing.JLabel lblDblPoint1;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblHour1;
    private javax.swing.JLabel lblMinutes;
    private javax.swing.JLabel lblMinutes1;
    private javax.swing.JLabel lblMonth1;
    private javax.swing.JLabel lblPoint1;
    private javax.swing.JLabel lblPoint2;
    private javax.swing.JLabel lblPoint3;
    private javax.swing.JLabel lblPoint4;
    private javax.swing.JLabel lblStartDay;
    private javax.swing.JLabel lblStartMonth;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblYear1;
    // End of variables declaration//GEN-END:variables
}
